# Generated by Django 4.0.6 on 2022-07-28 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("address_book", "0002_rename_ing_address_lng"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="lat",
        ),
        migrations.RemoveField(
            model_name="address",
            name="lng",
        ),
    ]
