# Generated by Django 4.0.6 on 2022-07-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address_book", "0003_remove_address_lat_remove_address_lng"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="raw_address",
            field=models.CharField(default="address", max_length=300),
        ),
    ]
