[default]
GMAPS_API_KEY="AIzaSyD2i-XugVBME63U6sMDyRmjfyLAGaVWOcM"
SENTRY_LINK="https://ef0db688876b46228a0aec573f30694b@o1337398.ingest.sentry.io/6607151"
SECRET_KEY="dmo)#3&bte$!jp!k*x4tb9fbs733@pt!$26t@s0r^y0a3mp2n4"