version: "3"
services:
  postgres:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]

  address_keeper_d:
    build:
      context: .
      dockerfile: address_keeper_d/Dockerfile
    restart: always
    volumes:
      - /address_book/static:/static
    environment:
      - IS_PRODUCTION=True
      - DJANGO_STATIC_ROOT="/static"
    env_file:
      - .env
    ports:
      - "8000:8000"
    links:
      - postgres:postgres
    depends_on:
      - postgres

  nginx:
    build: ./nginx
    volumes:
      - /address_book/static:/static
    ports:
      - "80:80"
    depends_on:
      - address_keeper_d